name: dropthenumber
description: A game to play 2048 vertically.
publish_to: "none"
version: 1.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flame: ^0.29.4
  flutter_screenutil: ^5.0.0+2
  sprintf: "^4.0.0"
  audioplayers: ^0.18.3
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/image/startPage/
    - assets/audio/
    - assets/video/verticalSuperpower/
    - assets/video/horizontalSuperpower/
  fonts:
  - family: DancingScript
    fonts:
    - asset: assets/Dancing_Script/dancing_script.ttf

